import type { BoardCandidate, ClientOverview, RoleBoard } from "./types";

// Entirely fictional sample data for the portal preview page.
const base = {
  verified_notice: null,
  verified_relocation: null,
  recommendation: null,
  open_to_relocation: null,
  work_mode: "Hybrid",
  category: "b2b_sales",
  secondary_sub_domains: [],
  ai_passport: null,
  resume_file_url: null,
  stage: "submitted",
  stage_updated_at: null,
  shortlisted_at: "2026-10-01T09:30:00Z",
  client_feedback: null,
  requested_interview_at: null,
  confirmed_interview_at: null,
  cv_roles: null,
  cv_tools: [],
  cv_education: null,
  cv_certifications: [],
  career_timeline: null,
  ai_checks: null,
} satisfies Partial<BoardCandidate>;

const candidates: BoardCandidate[] = [
  {
    ...base,
    link_id: "d1",
    candidate_id: "c1",
    full_name: "Aarav Menon",
    current_job_title: "Senior Account Executive",
    current_employer: "Cloudwise Systems",
    current_location: "Bengaluru",
    total_experience_years: 6,
    expected_fixed_ctc: 26,
    notice_period: "30 days",
    verified_notice: "Yes",
    verified_relocation: "Yes",
    recommendation: "Strong Fit",
    open_to_relocation: "Yes",
    sub_domain: "SaaS (horizontal)",
    industries: ["Fintech", "SaaS / Cloud Software", "E-commerce"],
    ai_summary:
      "Six years selling B2B SaaS to mid-market and enterprise buyers, currently a Senior AE at Cloudwise Systems. He has beaten quota in each of the last three years and runs the full cycle from outbound to close.",
    ai_passport: { resume_highlights: ["Closed a ₹83L annual number at 128% of quota last year.", "Won 11 new logos in a territory he opened from scratch.", "Runs security and procurement reviews himself."] },
    selling: {
      sells_now: ["SaaS (horizontal)"],
      motion: ["Outbound enterprise", "Inbound mid-market"],
      deal_size: "₹25L – ₹50L",
      quota: "100-120%",
      revenue_snapshot: { target: "₹75L – ₹1Cr / annum", achievement: "110%+" },
      style: "Hunter",
      customer_segment_sold: ["Mid-Market", "Enterprise"],
      crm_tools: ["Salesforce", "LinkedIn Sales Navigator"],
    },
    cv_roles: [
      { title: "Senior Account Executive", company: "Cloudwise Systems", start: "2024-01", is_current: true, sells: "Workflow automation software", quota_or_target: "₹75L", achievement: "128% of quota", deal_size: "₹32L avg", evidence: "Owns a territory across South India; closes full-cycle deals with CFOs and heads of operations." },
      { title: "Account Executive", company: "Ledgerly", start: "2021-06", end: "2023-12", sells: "Accounting software for mid-market", quota_or_target: "₹42L", achievement: "104% of quota", evidence: "Carried a ₹42L number in a smaller territory before moving up." },
    ],
    ai_checks: {
      must: [
        { requirement: "Sold to enterprise buyers", status: "met", evidence: "Runs deals with CFOs and heads of operations at 500+ person companies.", question: null },
        { requirement: "Owned a quota above ₹50L", status: "met", evidence: "₹75L annual quota, 128% attainment.", question: null },
      ],
      good: [{ requirement: "Experience selling to fintech", status: "doubt", evidence: null, question: "Has he sold to banks directly, or only fintech start-ups?" }],
    },
  },
  {
    ...base,
    link_id: "d2",
    candidate_id: "c2",
    full_name: "Diya Kapoor",
    current_job_title: "Account Executive",
    current_employer: "Pixelforge",
    current_location: "Pune",
    total_experience_years: 5,
    expected_fixed_ctc: 28,
    notice_period: "60 days",
    open_to_relocation: "Yes",
    sub_domain: "SaaS (horizontal)",
    industries: ["SaaS / Cloud Software", "Media / Advertising / MarTech"],
    ai_summary: "Five years in B2B SaaS sales, strongest in inbound mid-market deals. Open to moving to Bengaluru for the right role.",
    selling: { sells_now: ["SaaS (horizontal)"], motion: ["Inbound mid-market"], deal_size: "₹10L – ₹25L", quota: "90-100%", style: "Farmer" },
    client_feedback: "interested",
  },
  {
    ...base,
    link_id: "d3",
    candidate_id: "c3",
    full_name: "Karan Bhatia",
    current_job_title: "Enterprise Sales Manager",
    current_employer: "Orbit Data",
    current_location: "Bengaluru",
    total_experience_years: 8,
    expected_fixed_ctc: 30,
    notice_period: "90 days",
    verified_notice: "Yes",
    recommendation: "Strong Fit",
    sub_domain: "Data & analytics platforms",
    industries: ["Data & Analytics Platforms", "Fintech"],
    ai_summary: "Eight years selling data platforms to large enterprises. Leads a team of three and still carries his own number.",
    selling: { sells_now: ["Data & analytics platforms"], motion: ["Outbound enterprise"], deal_size: "₹50L+", quota: "100-120%", style: "Hunter", role_level: "Team lead" },
    stage: "client_interview",
    client_feedback: "interview_requested",
    requested_interview_at: "2026-10-09T11:00:00Z",
    confirmed_interview_at: "2026-10-09T11:00:00Z",
  },
  {
    ...base,
    link_id: "d4",
    candidate_id: "c4",
    full_name: "Meera Iyer",
    current_job_title: "Business Development Manager",
    current_employer: "Greenleaf Telecom",
    current_location: "Chennai",
    total_experience_years: 3,
    expected_fixed_ctc: 34,
    notice_period: "30 days",
    open_to_relocation: "Maybe",
    sub_domain: "Telecom services",
    category: "b2b_sales",
    industries: ["Telecom"],
    ai_summary: "Three years selling connectivity services to SMEs. Strong on relationships; less exposure to software sales.",
    selling: { sells_now: ["Telecom services"], motion: ["Outbound SMB"], deal_size: "₹3L – ₹10L", quota: "90-100%" },
  },
  {
    ...base,
    link_id: "d5",
    candidate_id: "c5",
    full_name: "Rohan Saxena",
    current_job_title: "Key Account Manager",
    current_employer: "Finlytics",
    current_location: "Bengaluru",
    total_experience_years: 7,
    expected_fixed_ctc: 24,
    notice_period: "30 days",
    sub_domain: "SaaS (vertical / industry)",
    industries: ["Fintech", "SaaS / Cloud Software"],
    ai_summary: "Seven years in account management and expansion selling for a fintech SaaS company.",
    selling: { sells_now: ["SaaS (vertical / industry)"], motion: ["Install-base expansion"], deal_size: "₹10L – ₹25L", quota: "100-120%" },
  },
  {
    ...base,
    link_id: "d6",
    candidate_id: "c6",
    full_name: "Sana Qureshi",
    current_job_title: "Senior Account Executive",
    current_employer: "Vantage Cloud",
    current_location: "Hyderabad",
    total_experience_years: 6,
    expected_fixed_ctc: 25,
    notice_period: "30 days",
    sub_domain: "SaaS (horizontal)",
    industries: ["SaaS / Cloud Software"],
    ai_summary: "Six years selling cloud software to mid-market buyers.",
    stage: "rejected",
    client_feedback: "not_interested",
    selling: { sells_now: ["SaaS (horizontal)"], deal_size: "₹10L – ₹25L", quota: "90-100%" },
  },
];

export const demoBoard: RoleBoard = {
  role: {
    id: "demo",
    role_title: "Enterprise Account Executive · B2B SaaS",
    category: "b2b_sales",
    sub_domain: "SaaS (horizontal)",
    sub_domains: ["SaaS (horizontal)", "SaaS (vertical / industry)"],
    city: "Bengaluru",
    cities: ["Bengaluru"],
    experience_min: 4,
    experience_max: 8,
    budget_min: 20,
    budget_max: 30,
    must_haves: ["Sold to enterprise buyers", "Owned a quota above ₹50L"],
    good_to_haves: ["Experience selling to fintech"],
    work_mode: "Hybrid",
    status: "open",
    headcount: 1,
    created_at: "2026-09-20T09:00:00Z",
    selling_style: "Hunter",
    industries_sold_to: ["Fintech"],
  },
  candidates,
};

export const demoOverview: ClientOverview = {
  mandates: [
    { id: "demo", role_title: "Enterprise Account Executive · B2B SaaS", category: "b2b_sales", sub_domain: "SaaS (horizontal)", city: "Bengaluru", status: "open", experience_min: 4, experience_max: 8, budget_min: 20, budget_max: 30, headcount: 1, created_at: "2026-09-20T09:00:00Z", shortlisted: 6, to_review: 3, interested: 1, interviewing: 1, hired: 0 },
    { id: "demo-2", role_title: "Inside Sales Lead · Mid-Market", category: "b2b_sales", sub_domain: "SaaS (horizontal)", city: "Mumbai", status: "open", experience_min: 3, experience_max: 6, budget_min: 14, budget_max: 20, headcount: 2, created_at: "2026-09-28T09:00:00Z", shortlisted: 4, to_review: 4, interested: 0, interviewing: 0, hired: 0 },
    { id: "demo-3", role_title: "Regional Sales Head · North", category: "b2b_sales", sub_domain: "Data & analytics platforms", city: "Delhi", status: "filled", experience_min: 10, experience_max: 15, budget_min: 45, budget_max: 60, headcount: 1, created_at: "2026-07-02T09:00:00Z", shortlisted: 5, to_review: 0, interested: 0, interviewing: 0, hired: 1 },
  ],
  upcoming: [{ link_id: "d3", mandate_id: "demo", role_title: "Enterprise Account Executive · B2B SaaS", full_name: "Karan Bhatia", at: "2026-10-09T11:00:00Z", confirmed: true }],
};
