export const openToRelocationOptions = ["OPEN_TO_RELOCATION", "NOT_OPEN_TO_RELOCATION"] as const;

export const indianStates = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const functionDepartmentOptions = [
  "-None-",
  "Sales",
  "Marketing",
  "Operations",
  "Customer Support",
  "Business Development",
  "Finance",
  "Human Resources (HR)",
  "Legal & Compliance",
  "Administration",
  "Information Technology (IT)",
  "Product Management",
  "Engineering / Technology",
  "Design",
  "Strategy",
  "Procurement",
  "Supply Chain",
  "Logistics & Distribution",
  "Manufacturing / Production",
  "Quality Assurance / Quality Control (QA/QC)",
  "Research & Development (R&D)",
  "Project Management",
  "Training & Development",
  "Learning & Development (L&D)",
  "Data & Analytics",
  "Business Intelligence",
  "Risk & Governance",
  "Internal Audit",
  "Corporate Communications",
  "Public Relations (PR)",
  "Investor Relations",
  "Innovation & Digital Transformation",
  "Sustainability & ESG",
  "Facilities Management",
  "Security & Surveillance",
  "Customer Success",
  "Talent Acquisition / Recruitment",
  "Compensation & Benefits",
  "Performance Management",
  "Technical Support",
  "Presales / Solutions Engineering",
  "Content Management",
  "Creative / Branding",
  "Events & Activation",
  "Vendor Management",
  "Compliance & Regulatory Affairs",
  "Franchise / Channel Management",
  "Enterprise Architecture",
  "Cloud Infrastructure",
  "DevOps / Site Reliability Engineering (SRE)",
  "Cybersecurity",
  "Product Design / UX",
  "Legal Affairs / Corporate Law",
  "Taxation & Auditing",
  "Treasury / Fund Management",
  "Export / Import / International Business",
  "Government Relations / Liaison",
  "Policy & Advocacy",
  "Healthcare & Clinical Operations (for Med/Health)",
  "Merchandising (for Retail/E-commerce)",
  "E-commerce Operations",
  "Customer Experience (CX)",
  "Knowledge Management",
  "CRM / Lead Management",
  "Field Operations",
  "Inside Sales",
  "Real Estate / Property Management",
  "Plant Operations",
  "Compliance & Ethics",
  "Mobility / Transportation",
  "Helpdesk / IT Support",
  "Change Management",
  "Business Process Reengineering",
  "Crowdsourcing / Open Innovation (for new-age firms)",
  "Intellectual Property / Patents",
  "Media & Broadcasting (for content companies)",
  "Other",
] as const;

export const currentJobTitleOptions = [
  "-None-",
  "Fresher",
  "Project-Lead",
  "Project-Manager",
  "Sales Executive",
  "Sales Manager",
  "Business Development Executive",
  "Business Development Manager",
  "Inside Sales Representative",
  "Key Account Manager",
  "Territory Sales Manager",
  "Area Sales Manager",
  "Channel Sales Executive",
  "Pre-Sales Consultant",
  "Field Sales Executive",
  "Sales Trainer",
  "Regional Sales Manager",
  "International Sales Manager",
  "Telesales Executive",
  "Direct Sales Associate",
  "Institutional Sales Executive",
  "Sales Coordinator",
  "Marketing Executive",
  "Digital Marketing Manager",
  "SEO Executive",
  "Content Writer",
  "Social Media Manager",
  "Brand Manager",
  "Growth Hacker",
  "Performance Marketing Manager",
  "Email Marketing Executive",
  "Copywriter",
  "Marketing Analyst",
  "PPC Specialist",
  "Affiliate Marketing Manager",
  "Marketing Automation Specialist",
  "Influencer Marketing Executive",
  "Customer Support Executive",
  "Customer Success Manager",
  "Technical Support Engineer",
  "Helpdesk Associate",
  "Operations Executive",
  "Operations Manager",
  "MIS Executive",
  "Back Office Executive",
  "Chat Support Agent",
  "Voice Process Executive",
  "Non-Voice Process Associate",
  "Service Delivery Manager",
  "BPO Executive",
  "Quality Analyst - Customer Service",
  "Accountant",
  "Accounts Executive",
  "Finance Manager",
  "Tax Consultant",
  "Financial Analyst",
  "Payroll Executive",
  "Cost Accountant",
  "Internal Auditor",
  "Accounts Payable Executive",
  "Accounts Receivable Executive",
  "Chartered Accountant",
  "Credit Control Executive",
  "Fund Manager",
  "Reconciliation Specialist",
  "HR Executive",
  "HR Manager",
  "Recruitment Executive",
  "Talent Acquisition Specialist",
  "HR Business Partner",
  "Training & Development Executive",
  "Onboarding Specialist",
  "Compensation & Benefits Analyst",
  "Employee Relations Executive",
  "HR Generalist",
  "HR Operations Executive",
  "Campus Recruiter",
  "Technical Recruiter",
  "IT Recruiter",
  "Compliance & Labor Law Officer",
  "Software Engineer",
  "Full Stack Developer",
  "Backend Developer",
  "Frontend Developer",
  "Mobile App Developer",
  "DevOps Engineer",
  "QA Engineer",
  "Manual Tester",
  "Automation Tester",
  "UI/UX Designer",
  "Product Manager",
  "Project Manager",
  "Technical Architect",
  "Data Analyst",
  "Data Scientist",
  "AI/ML Engineer",
  "Cybersecurity Analyst",
  "Network Engineer",
  "System Administrator",
  "Database Administrator",
  "Cloud Engineer",
  "Office Assistant",
  "Receptionist",
  "Executive Assistant",
  "Admin Executive",
  "Front Desk Executive",
  "Facility Manager",
  "Office Manager",
  "Data Entry Operator",
  "Personal Assistant",
  "Logistics Executive",
  "Supply Chain Manager",
  "Inventory Manager",
  "Warehouse Manager",
  "Procurement Executive",
  "Purchase Manager",
  "Transport Coordinator",
  "Store Incharge",
  "Import Export Executive",
  "Dispatch Executive",
  "Vendor Manager",
  "Mechanical Engineer",
  "Electrical Engineer",
  "Civil Engineer",
  "Maintenance Engineer",
  "Production Engineer",
  "Design Engineer",
  "Quality Control Engineer",
  "Project Engineer",
  "Instrumentation Engineer",
  "HVAC Engineer",
  "CAD Draughtsman",
  "Staff Nurse",
  "Pharmacist",
  "Lab Technician",
  "Medical Representative",
  "Physiotherapist",
  "Doctor",
  "Radiologist",
  "Pathologist",
  "Clinical Research Associate",
  "Medical Coder",
  "Dental Assistant",
  "Healthcare Administrator",
  "Teacher",
  "Subject Matter Expert",
  "School Principal",
  "Academic Counselor",
  "Online Tutor",
  "Instructional Designer",
  "Curriculum Developer",
  "IELTS Trainer",
  "Soft Skills Trainer",
  "Corporate Trainer",
  "Learning & Development Specialist",
  "Graphic Designer",
  "Visual Designer",
  "Motion Graphic Artist",
  "Video Editor",
  "UI Designer",
  "Animator",
  "Creative Director",
  "Art Director",
  "Fashion Designer",
  "Interior Designer",
  "Illustrator",
  "Legal Advisor",
  "Corporate Lawyer",
  "Compliance Officer",
  "Legal Assistant",
  "Company Secretary",
  "Contract Manager",
  "Legal Associate",
  "IP Analyst",
  "Regulatory Affairs Specialist",
  "Relationship Manager",
  "Branch Manager",
  "Loan Officer",
  "Credit Analyst",
  "Investment Advisor",
  "Underwriter",
  "Insurance Sales Executive",
  "Claims Manager",
  "Wealth Manager",
  "Risk Analyst",
  "Production Supervisor",
  "Plant Head",
  "CNC Operator",
  "Machinist",
  "Quality Inspector",
  "Assembly Line Worker",
  "Safety Officer",
  "Packaging Executive",
  "Tool Room Engineer",
  "Store Manager",
  "Visual Merchandiser",
  "Retail Sales Executive",
  "Inventory Controller",
  "Ecommerce Operations Executive",
  "Customer Support - Ecommerce",
  "Category Manager",
  "Merchandising Executive",
  "Buyer",
  "Hotel Manager",
  "Front Office Executive",
  "Housekeeping Executive",
  "Travel Consultant",
  "Guest Relations Executive",
  "Airline Ticketing Executive",
  "Ground Staff",
  "Cabin Crew",
  "Chef",
  "Food & Beverage Executive",
  "Content Creator",
  "News Anchor",
  "Video Journalist",
  "Reporter",
  "Scriptwriter",
  "Editor",
  "Radio Jockey",
  "Public Relations Officer",
  "Event Manager",
  "Cinematographer",
  "General Manager - Sales",
  "General Manager - Operations",
  "General Manager - HR",
  "General Manager - Projects",
  "AVP - Sales / Marketing / Ops / HR / Tech",
  "Senior Manager - (Function)",
  "AGM - (Function)",
  "DGM - (Function)",
  "Management Consultant",
  "Strategy Consultant",
  "Digital Transformation Lead",
  "Innovation Lead",
  "Automation Lead",
  "ESG Officer (Environmental, Social, Governance)",
  "Diversity & Inclusion Officer",
  "Remote Operations Lead",
  "Data Governance Manager",
  "Business Intelligence Head",
  "Analytics Head",
  "Cloud Strategy Head",
  "AI/ML Strategy Head",
  "ESG Compliance Head",
  "Sustainability Officer",
  "Public Policy Head",
  "Vice President - Sales",
  "Vice President - Marketing",
  "Vice President - Operations",
  "Vice President - Finance",
  "Vice President - HR",
  "Vice President - Technology",
  "Vice President - Customer Success",
  "Vice President - Product",
  "Vice President - Growth",
  "Director - Sales",
  "Director - Marketing",
  "Director - Operations",
  "Director - Finance",
  "Director - Human Resources",
  "Director - Product",
  "Director - Customer Experience",
  "Director - Engineering",
  "Director - Analytics",
  "Director - Strategy",
  "National Sales Head",
  "Business Head",
  "Sales Head",
  "Marketing Head",
  "HR Head",
  "Product Head",
  "Operations Head",
  "Training Head",
  "Customer Support Head",
  "Technical Head",
  "Creative Head",
  "Engineering Head",
  "Procurement Head",
  "Design Head",
  "Talent Acquisition Head",
  "Inside Sales Head",
  "Field Sales Head",
  "Regional Business Head",
  "Zonal Head",
  "Country Head",
  "Growth Head",
  "Finance Controller",
  "Factory Head",
  "Legal Head",
  "Admin Head",
  "Delivery Head",
  "Program Head",
  "Learning & Development Head",
  "Chief Executive Officer (CEO)",
  "Chief Operating Officer (COO)",
  "Chief Financial Officer (CFO)",
  "Chief Marketing Officer (CMO)",
  "Chief Technology Officer (CTO)",
  "Chief Sales Officer (CSO)",
  "Chief Human Resources Officer (CHRO)",
  "Chief Product Officer (CPO)",
  "Chief Experience Officer (CXO)",
  "Chief Information Officer (CIO)",
  "Chief Compliance Officer (CCO)",
  "Chief Strategy Officer",
  "Chief Growth Officer",
  "Chief Data Officer",
  "Chief Risk Officer",
  "Chief Innovation Officer",
  "Other (Not in the list)",
] as const;

export const highestQualificationOptions = [
  "-None-",
  "10th Pass",
  "12th Pass",
  "ITI - Fitter",
  "ITI - Electrician",
  "ITI - Welder",
  "ITI - Mechanic",
  "Diploma - Mechanical Engineering",
  "Diploma - Civil Engineering",
  "Diploma - Electrical Engineering",
  "Diploma - Electronics & Communication",
  "Diploma - Automobile Engineering",
  "Diploma - Computer Science",
  "Polytechnic Diploma",
  "Bachelor of Arts (BA)",
  "Bachelor of Science (BSc)",
  "Bachelor of Commerce (BCom)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Computer Applications (BCA)",
  "Bachelor of Engineering (BE)",
  "Bachelor of Technology (BTech)",
  "Bachelor of Architecture (BArch)",
  "Bachelor of Pharmacy (BPharm)",
  "Bachelor of Hotel Management (BHM)",
  "Bachelor of Education (BEd)",
  "Bachelor of Design (BDes)",
  "Bachelor of Fine Arts (BFA)",
  "Bachelor of Laws (LLB)",
  "Bachelor of Social Work (BSW)",
  "Bachelor of Physiotherapy (BPT)",
  "Bachelor of Veterinary Science (BVSc)",
  "Bachelor of Ayurvedic Medicine & Surgery (BAMS)",
  "Bachelor of Homeopathic Medicine & Surgery (BHMS)",
  "Bachelor of Unani Medicine & Surgery (BUMS)",
  "Bachelor of Dental Surgery (BDS)",
  "Bachelor of Medicine and Bachelor of Surgery (MBBS)",
  "Bachelor of Journalism and Mass Communication (BJMC)",
  "Master of Arts (MA)",
  "Master of Science (MSc)",
  "Master of Commerce (MCom)",
  "Master of Business Administration (MBA)",
  "Master of Computer Applications (MCA)",
  "Master of Engineering (ME)",
  "Master of Technology (MTech)",
  "Master of Pharmacy (MPharm)",
  "Master of Education (MEd)",
  "Master of Design (MDes)",
  "Master of Social Work (MSW)",
  "Master of Journalism and Mass Communication (MJMC)",
  "Master of Fine Arts (MFA)",
  "Master of Laws (LLM)",
  "Chartered Accountant (CA)",
  "Company Secretary (CS)",
  "Cost & Management Accountant (CMA/ICWA)",
  "Certified Financial Planner (CFP)",
  "Certified Public Accountant (CPA)",
  "Doctor of Philosophy (PhD)",
  "Doctor of Medicine (MD)",
  "Master of Surgery (MS)",
  "Diploma in Nursing",
  "Post Graduate Diploma in Management (PGDM)",
  "Post Graduate Diploma in Computer Applications (PGDCA)",
  "International Baccalaureate (IB Diploma)",
  "International General Certificate of Secondary Education (IGCSE)",
  "Professional Certification - Digital Marketing",
  "Professional Certification - Data Science",
  "Professional Certification - Project Management (PMP)",
  "Professional Certification - HR/Recruitment",
  "Professional Certification - Finance/Accounts",
  "Professional Certification - Sales",
  "Professional Certification - Software Development",
  "Professional Certification - Networking",
  "Professional Certification - UI/UX",
  "Professional Certification - Graphic Design",
  "Professional Certification - Foreign Language",
  "Foreign University - Bachelor's Degree",
  "Foreign University - Master's Degree",
  "Foreign University - MBA",
  "No Formal Education",
  "Other (Not in the list)",
] as const;

export const domainOptions = [
  "Aerospace and Defense",
  "Agriculture",
  "Automotive",
  "Banking and Financial Services",
  "Biotechnology",
  "Chemicals",
  "Construction",
  "Consumer Goods",
  "Education",
  "Energy and Utilities",
  "Entertainment and Media",
  "Healthcare and Pharmaceuticals",
  "Information Technology",
  "Insurance",
  "Manufacturing",
  "Mining",
  "Real Estate",
  "Retail and E-commerce",
  "Telecommunications",
  "Transportation and Logistics",
  "Travel and Hospitality",
] as const;
