export interface SkillOptionGroup {
  category: string;
  skills: string[];
}

export const skillOptionGroups: SkillOptionGroup[] = [
  {
    category: "Core Sales",
    skills: [
      "Lead Generation",
      "Prospecting",
      "Cold Calling",
      "Cold Emailing",
      "WhatsApp Outreach",
      "Qualifying Leads",
      "Needs Analysis",
      "Solution Pitching",
      "Presentation Skills",
      "Product Demonstration",
      "Objection Handling",
      "Negotiation",
      "Closing",
      "Follow-up Management",
      "Upselling",
      "Cross-Selling",
      "Referral Selling",
      "Pipeline Management",
      "Sales Forecasting",
      "CRM Management",
      "Quota Achievement",
      "Territory Planning",
      "Account Mapping",
      "Competitive Analysis",
    ],
  },
  {
    category: "B2B - SMB & Mid-Market",
    skills: [
      "Inside Sales (B2B)",
      "Outbound Sequencing",
      "Email Campaign Sales",
      "LinkedIn Outreach",
      "Short-Cycle Selling",
      "Trial / POC Conversion",
      "SMB Account Management",
      "Renewal Management",
      "Churn Prevention",
      "Product-Led Growth (PLG)",
      "Self-Serve Onboarding",
      "Demo-to-Close",
      "Transactional B2B Sales",
    ],
  },
  {
    category: "B2B - Enterprise & Complex Deals",
    skills: [
      "Enterprise Sales",
      "Complex Sales Cycles",
      "C-Suite Engagement",
      "Multi-threading",
      "Strategic Account Planning",
      "Champion Building",
      "Value-Based Selling",
      "MEDDIC / MEDDPICC",
      "Challenger Selling",
      "RFP & Proposal Writing",
      "Contract Negotiation",
      "Legal & Procurement Navigation",
      "QBR Facilitation",
      "Land & Expand",
      "Competitive Displacement",
      "Political Mapping",
      "Executive Presentation",
      "EBC Facilitation",
      "Consultative Selling",
      "SPIN Selling",
      "Solution Selling",
      "ABM (Account-Based Marketing)",
      "Technical Sales Support",
      "Pre-Sales / Solutions Engineering",
    ],
  },
  {
    category: "Channel & Partner Sales",
    skills: [
      "Channel Development",
      "Partner Recruitment",
      "Partner Enablement & Training",
      "Distributor Management",
      "Dealer Network Management",
      "Reseller Management",
      "VAR / SI Management",
      "Channel Conflict Resolution",
      "MDF Management",
      "Co-selling with Partners",
      "Franchise Management",
      "DSA Network Management",
      "Vendor Empanelment",
      "Rate Contract Management",
      "Channel Partner ROI",
      "Sub-Distributor Management",
      "Broker Network Management",
    ],
  },
  {
    category: "Government & PSU Sales",
    skills: [
      "GeM Portal Sales",
      "GeM Catalog Optimization",
      "Tender Management",
      "L1 Bidding Strategy",
      "EMD & PBG Handling",
      "DGS&D Rate Contracts",
      "NSIC / MSME Knowledge",
      "Government Liaison",
      "Government Relationship Building",
      "Defence Sales",
      "Railway / PSU Sales",
      "Smart City Project Sales",
      "ARC Management",
      "CPPP Portal Knowledge",
      "Empanelment with Govt Bodies",
      "Municipal Corporation Sales",
      "State PSU Sales",
      "Central Govt Sales",
    ],
  },
  {
    category: "B2C Sales",
    skills: [
      "Retail Sales",
      "Counter Sales",
      "Walk-in Conversion",
      "Door-to-Door Sales",
      "Tele-Sales (Inbound)",
      "Tele-Sales (Outbound)",
      "Video / Virtual Sales",
      "Chat & WhatsApp Sales",
      "Social Selling",
      "D2C Sales",
      "App-Based Selling",
      "EMI Structuring",
      "Customer Onboarding",
      "Loan Sales",
      "Insurance Sales",
      "Bancassurance",
      "Investment Selling (MF/SIP)",
      "Real Estate Sales",
      "EdTech Counselling / Admission Sales",
      "CASA Sales",
      "Beat Planning",
      "Van Sales",
      "Modern Trade",
      "General Trade",
      "Merchandising & Planogram",
      "DSA Management",
      "Churn Reduction",
      "Loyalty Program Management",
      "Farmer Sales (Rural)",
      "Kiosk / Activation Sales",
    ],
  },
  {
    category: "International & US Market Skills",
    skills: [
      "US Enterprise Sales",
      "Outbound SDR / BDR (US)",
      "Account Executive (US AE)",
      "US SaaS Sales",
      "Named Account Selling",
      "Territory-Based AE",
      "APAC Sales",
      "Middle East Sales",
      "Cold Outreach (US Timezone)",
      "Sales Navigator Prospecting",
      "Gong / Chorus / Clari Usage",
      "US Procurement Navigation",
      "Multi-currency Deal Structuring",
      "UK / Europe Sales",
      "Offshore Sales Leadership",
      "Partner-Led Sales (US)",
    ],
  },
  {
    category: "Leadership & Management (Manager+ Only)",
    skills: [
      "Sales Team Building",
      "Hiring Salespeople",
      "Sales Coaching & Mentoring",
      "Performance Management",
      "Incentive Design",
      "Territory Design",
      "GTM Planning",
      "Revenue Operations (RevOps)",
      "Sales Enablement",
      "P&L Management",
      "Market Mapping",
      "Demand Generation Strategy",
      "Sales Process Design",
      "MIS & Reporting",
      "Budgeting & Cost Control",
      "Key Account Strategy",
      "Board-Level Presentations",
      "Sales Tech Stack Ownership",
      "M&A Due Diligence (Sales)",
      "Sales Ops Automation",
      "CRM Implementation",
    ],
  },
  {
    category: "Industry-Specific Skills",
    skills: [
      "Pharma Detailing",
      "KOL Management",
      "Doctor Relationship Management",
      "Hospital / Institutional Sales (Pharma)",
      "FMCG Distribution",
      "Primary & Secondary Sales",
      "Stockist / Sub-Stockist Management",
      "IT Infrastructure Sales",
      "Cloud Sales",
      "Cybersecurity Sales",
      "ERP / HRMS / CRM Software Sales",
      "Financial Product Sales (Generic)",
      "Wealth Management Sales",
      "Motor Insurance Sales",
      "Real Estate Channel Partners",
      "RERA Compliance Knowledge",
      "Logistics / Freight Sales",
      "3PL Sales",
      "Fleet Sales",
      "Industrial Equipment Sales",
      "Capital Goods Sales",
      "Project / Turnkey Sales",
      "AMC & Renewal Sales",
      "OEM Sales",
      "Commodity / Raw Material Sales",
      "Renewable Energy Sales",
    ],
  },
] as const;
